apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sumo-k8

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml  # Uncomment if using ingress
  # - postgres.yaml  # Uncomment if deploying PostgreSQL in cluster

commonLabels:
  app: sumo-k8-controller
  managed-by: kustomize

