apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sumo-k8-controller
  namespace: sumo-k8
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces", "resourcequotas", "limitranges"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "pods"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumo-k8-controller-cluster
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sumo-k8-controller
  namespace: sumo-k8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sumo-k8-controller
subjects:
- kind: ServiceAccount
  name: sumo-k8-controller
  namespace: sumo-k8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumo-k8-controller-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sumo-k8-controller-cluster
subjects:
- kind: ServiceAccount
  name: sumo-k8-controller
  namespace: sumo-k8

