apiVersion: v1
kind: ServiceAccount
metadata:
  name: sumo-k8-controller
  namespace: sumo-k8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sumo-k8-controller
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "configmaps", "resourcequotas", "limitranges", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sumo-k8-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sumo-k8-controller
subjects:
- kind: ServiceAccount
  name: sumo-k8-controller
  namespace: sumo-k8

